name: underline_otp_text_field
description: Underline otp text field .
version: 0.0.1
author: Ravi Ranjan <devbytes1024@gmail.com>
email:  devbytes1024@gmail.com
homepage: https://github.com/i-am-uranium/underline-otp-textfield

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  
